#!/bin/bash

# Define an array of kawaii welcome messages
KAWAII_MESSAGES=(
    "🍑 Konnichiwa, lovely! You brighten up the terminal! 🌟"
    "🌺 Welcome back, sweetie! Ready for some coding magic? ✨"
    "🐾 Ohayou, cute! Let’s make today super awesome! 💪"
    "🍡 Yatta! You’re the cutest coder around! 🌸"
    "🎀 Sugoi! Let’s sprinkle some kawaii on your terminal! 💫"
    "💞 Ganbatte! Your cuteness knows no bounds! 🌼"
    "🌟 Hello, angel! Let’s code with a smile! 😄"
    "🍓 Ohayo, darling! Time for some kawaii coding! 🐰"
    "🌸 You’re the cherry blossom of the terminal! 🌺"
    "🎉 Okaeri, star! Let’s rock this coding session! ✨"
    "🌷 Welcome back, sunshine! Let’s sparkle today! 💖"
    "🐰 Konnichiwa! You’re as adorable as a bunny! 🍰"
    "🍡 Sugoi! Let’s add some sweetness to your code! 🌟"
    "💖 Hello, cutie! Time to shine bright like a star! 🌼"
    "🌺 Ganbatte! You’re coding magic today! 🎀"
    "🍥 Ohayou, sweetheart! Let’s have a productive day! ✨"
    "🌸 Welcome, lovely! Your cuteness makes everything better! 💕"
    "🐾 Yatta! You’re the best coder ever! 🍑"
    "🌟 Konnichiwa, sunshine! Let’s make today amazing! 🎉"
    "🍓 Sugoi! Your kawaii energy is off the charts! 💖"
    "🎀 Ohayo, star! Time to conquer the terminal! 🌸"
    "💞 Welcome back, sweetie! Your cuteness is unmatched! 🌼"
    "🌷 Konnichiwa, angel! Let’s make some coding magic! ✨"
    "🐰 Sugoi! You’re as cute as a fluffy bunny! 🍡"
    "🍥 Ganbatte! Your kawaii charm lights up the terminal! 🌟"
    "🌺 Hello, darling! Ready to code with flair? 💖"
    "🎉 Ohayou, cutie! Let’s dive into some awesome coding! 🌸"
    "💖 Sugoi! You’re the cutest terminal star ever! 🌷"
    "🌼 Konnichiwa! Let’s code with a smile today! 🎀"
    "🍓 Welcome back, sunshine! Your kawaii vibes are perfect! 💫"
    "🐰 Ohayo, sweetie! You’re going to do amazing things today! 🍥"
    "🌟 Ganbatte! Your cuteness is unstoppable! 🎉"
    "🍡 Sugoi! Time to sprinkle some kawaii into your code! 🌸"
    "💞 Hello, darling! You make the terminal a happier place! 🌼"
    "🎀 Konnichiwa! Let’s code with style and cuteness! 🌟"
    "🌷 Welcome back, star! Your kawaii energy is inspiring! 💖"
    "🐰 Ohayo! You’re the cutest coder in town! 🍓"
    "🍥 Sugoi! Let’s create some coding magic together! 💫"
    "🌸 Ganbatte! You’re dazzlingly cute and awesome! 🌺"
    "🎉 Konnichiwa, sweetie! Ready to code with a smile? 🌼"
    "💖 Ohayo, angel! Your cuteness makes everything better! 🌷"
    "🍑 Sugoi! Let’s have a kawaii and productive day! 🎀"
    "🌟 Hello, darling! Your kawaii charm is unbeatable! 💞"
    "🌺 Welcome back, sunshine! You’re ready to sparkle! 🍡"
    "🐰 Ohayo, star! Time to shine bright and cute! 🍓"
    "🍥 Sugoi! Your kawaii energy is contagious! 🌟"
    "🌸 Ganbatte! You’re the sweetest coder ever! 💖"
    "🎀 Konnichiwa! Let’s sprinkle some kawaii into your work! 🌷"
    "💞 Ohayo, cutie! Your terminal skills are amazing! 🎉"
    "🌷 Welcome back, angel! Time to conquer with kawaii vibes! 🍑"
    "🐰 Sugoi! You’re a coding superstar with kawaii charm! 🍥"
    "🍓 Ganbatte! Your cuteness is the secret to your success! 🌼"
    "🌟 Konnichiwa! Let’s make today extra kawaii! 💖"
    "🌸 Ohayo, darling! Your kawaii energy is perfect! 🌺"
    "🎀 Sugoi! Ready to brighten up the terminal with your cuteness? 🍡"
    "💞 Welcome back, sweetie! You’re going to code with style! 🌷"
    "🌷 Konnichiwa! Your kawaii spirit is amazing today! 💫"
    "🐰 Ohayo! Let’s make today full of kawaii coding moments! 🍥"
    "🍑 Sugoi! You’re as sweet as a peach and ready to code! 🌸"
    "🌺 Hello, star! Your kawaii vibes are the best! 🎀"
    "🎉 Ohayo, sunshine! Let’s add some sparkle to your coding! 💖"
    "💖 Konnichiwa! Your cuteness makes everything brighter! 🍓"
    "🍡 Sugoi! Ready to spread kawaii magic on your terminal? 🌼"
    "🌟 Welcome back, cutie! You’re a coding superstar! 🎉"
    "🌷 Ohayo! Your kawaii charm lights up the terminal! 💞"
    "🐰 Ganbatte! You’re the cutest and most talented coder ever! 🌸"
    "🍥 Sugoi! Let’s make today super kawaii and productive! 🌺"
    "🌼 Hello, darling! Your cuteness is out of this world! 💖"
    "🎀 Konnichiwa! Ready for a day full of kawaii coding? 🌷"
    "💖 Ohayo! Your kawaii spirit is perfect for a productive day! 🍑"
    "🍓 Sugoi! Time to shine bright and kawaii in your terminal! 🌟"
    "🌸 Ganbatte! You’re as adorable as ever and ready to code! 💫"
    "🐰 Welcome back, sweetie! Let’s make today extra kawaii! 🍥"
    "🍥 Sugoi! Your kawaii energy is a coding superpower! 🎀"
    "🌷 Ohayo, star! Time to conquer with your kawaii charm! 💞"
    "💖 Konnichiwa! You’re the most adorable coder around! 🌺"
    "🌟 Welcome back, angel! Your kawaii vibes are perfect! 🍓"
    "🎉 Ohayo! Your cuteness is going to make today amazing! 🌸"
    "🍑 Sugoi! Let’s add some kawaii magic to your code! 🌷"
    "🌼 Konnichiwa, sunshine! You’re ready to code with flair! 💖"
    "🌺 Ohayo, sweetie! Your kawaii charm is inspiring! 🍥"
    "🐰 Sugoi! You’re a kawaii coding superstar! 🌟"
    "🍡 Welcome back! Let’s sprinkle some kawaii into your work! 🎀"
    "🌸 Ganbatte! Your cuteness makes coding a joy! 💞"
    "🎉 Ohayo! Your kawaii spirit is perfect for a great day! 🌼"
    "💖 Konnichiwa! Let’s make today sparkle with your charm! 🍓"
    "🍑 Sugoi! You’re the sweetest coder ever! 🌸"
    "🌟 Welcome back, darling! Your kawaii vibes are amazing! 🌷"
    "🌺 Ohayo! Ready to brighten up the terminal with cuteness? 🍥"
    "🎀 Sugoi! Let’s make today full of kawaii coding moments! 💖"
    "💞 Konnichiwa! Your terminal skills are as cute as you! 🌼"
    "🍡 Ohayo! Time to conquer with kawaii and charm! 🎉"
    "🌸 Sugoi! Your cuteness makes every coding day special! 💞"
    "🐰 Welcome back, angel! You’re going to shine bright today! 🌷"
    "🍑 Konnichiwa! Let’s add some kawaii to your terminal work! 🌟"
    "🌺 Ohayo, sweetie! You’re the cutest coder ever! 💖"
    "🎀 Sugoi! Time to sprinkle some kawaii into your day! 🍥"
    "💖 Ganbatte! Your kawaii charm is the key to success! 🌼"
    "🌟 Konnichiwa! Your cuteness is making today amazing! 🍓"
    "🍡 Ohayo, darling! Ready to shine with kawaii vibes? 🌸"
    "🌷 Sugoi! Your kawaii energy makes coding a joy! 💞"
    "🐰 Welcome back, cutie! You’re going to do amazing things today! 🌺"
    "🍑 Ohayo! Let’s make today kawaii and productive! 🌟"
    "💖 Sugoi! You’re the sweetest and most talented coder around! 🍓"
    "🌸 Ganbatte! Your kawaii charm is unstoppable! 💫"
    "🎀 Konnichiwa! Let’s spread some kawaii magic in your terminal! 🌷"
    "🍡 Ohayo! Your cuteness is the highlight of the day! 💖"
    "🌼 Sugoi! Time to code with your kawaii energy! 🎉"
    "🌟 Welcome back, angel! You’re going to shine brightly today! 🍥"
    "🐰 Ohayo, sweetie! Your kawaii spirit is perfect for coding! 🍑"
    "🍓 Sugoi! Let’s make today extra kawaii and productive! 🌸"
    "🎀 Konnichiwa! Your terminal skills are cuteness overload! 💞"
    "🌷 Ohayo! Ready to conquer with kawaii vibes and charm? 🌟"
    "💖 Sugoi! Your cuteness is the key to a great coding day! 🌼"
    "🌺 Welcome back, darling! Your kawaii energy is amazing! 🍥"
    "🍑 Ohayo! Let’s code with a touch of kawaii magic! 🌷"
    "🐰 Sugoi! Your terminal skills are as adorable as you are! 💖"
    "🌸 Ganbatte! Your kawaii charm is a coding superpower! 🎀"
    "🍓 Konnichiwa! Time to sprinkle some kawaii into your work! 🌼"
    "🌟 Ohayo, cutie! Your kawaii spirit makes coding fun! 🍑"
    "💞 Sugoi! You’re the cutest coder in the terminal! 🌸"
    "🌺 Welcome back! Let’s make today extra kawaii and productive! 💖"
    "🍥 Ohayo! Your cuteness makes everything brighter! 🌟"
    "🌷 Konnichiwa, angel! Ready to shine with kawaii energy? 🍡"
    "🐰 Sugoi! You’re a kawaii coding superstar! 🌼"
    "💖 Ohayo! Your kawaii charm is perfect for a great day! 🌸"
    "🍑 Ganbatte! Your cuteness makes coding amazing! 💫"
    "🌸 Welcome back, darling! Time to shine with kawaii vibes! 🎀"
    "🍓 Sugoi! Let’s add some kawaii magic to your terminal work! 🌟"
    "🌺 Konnichiwa! Your cuteness is going to make today amazing! 💞"
    "🎉 Ohayo! Time to sprinkle some kawaii into your coding! 🍥"
    "💖 Sugoi! You’re the sweetest and most talented coder around! 🌷"
    "🌼 Welcome back, sweetie! Your kawaii energy is perfect for coding! 🍑"
    "🐰 Konnichiwa! Ready to brighten up the terminal with cuteness? 🌸"
    "🍡 Sugoi! Let’s make today extra kawaii and productive! 💫"
    "🌟 Ohayo! Your kawaii charm makes coding fun and exciting! 🍓"
    "🌺 Ganbatte! Your cuteness is a coding superpower! 🌼"
    "🎀 Welcome back, angel! Let’s sprinkle some kawaii into your work! 💖"
    "🍑 Sugoi! You’re the cutest coder ever! 🌷"
    "🌸 Ohayo! Ready to code with a touch of kawaii magic? 🌟"
    "💖 Konnichiwa! Your kawaii vibes are going to make today amazing! 🎀"
    "🍥 Sugoi! Let’s add some kawaii energy to your coding! 🌼"
    "🌺 Welcome back, cutie! Your kawaii charm is perfect for coding! 🍑"
    "🐰 Ohayo! Time to shine bright with kawaii vibes! 🍡"
    "🍓 Sugoi! You’re the sweetest and most kawaii coder ever! 💖"
    "🌟 Konnichiwa! Let’s make today extra kawaii and productive! 🌷"
    "💞 Ohayo! Your cuteness is the highlight of the terminal! 🌸"
    "🌼 Sugoi! Time to conquer with kawaii vibes and charm! 🎉"
    "🍑 Welcome back, darling! Your kawaii energy is inspiring! 💫"
    "🌺 Ohayo! Your cuteness makes everything better! 🍥"
    "🐰 Konnichiwa! Ready to sprinkle some kawaii into your work? 🌟"
    "🍡 Sugoi! You’re a kawaii coding superstar! 💖"
    "🎀 Welcome back, cutie! Your kawaii charm is perfect for today! 🌼"
    "🌸 Ohayo! Time to add some kawaii magic to your coding! 🍑"
    "💖 Sugoi! Your cuteness is making the terminal sparkle! 🌷"
    "🌺 Ganbatte! You’re the cutest and most talented coder ever! 🍥"
    "🌟 Konnichiwa! Let’s brighten up the terminal with kawaii vibes! 💞"
    "🍓 Ohayo! Your kawaii spirit is perfect for a productive day! 🎀"
    "🌼 Sugoi! Let’s make today extra kawaii and awesome! 🌸"
    "🐰 Welcome back, angel! Your cuteness makes coding amazing! 💖"
    "🍑 Sugoi! Time to shine bright and kawaii in the terminal! 🌷"
    "🌺 Konnichiwa! Your kawaii charm is unstoppable today! 🍥"
    "🎉 Ohayo! Ready to sprinkle some kawaii magic on your code? 🌟"
    "💖 Sugoi! You’re the sweetest and most adorable coder ever! 🍓"
    "🌸 Welcome back, cutie! Let’s make today extra kawaii and fun! 💫"
    "🍡 Ohayo! Your kawaii energy is perfect for a great coding day! 🌼"
)


# Select a random message
RANDOM_MESSAGE=${KAWAII_MESSAGES[RANDOM % ${#KAWAII_MESSAGES[@]}]}

# Display the random kawaii message
echo $RANDOM_MESSAGE
